### ISSUE TITLE
`getConformanceResults` returns an empty array for packages without `commonality.json`

### ISSUE THREAD

**Issue by IKatsuba** [commonalityco/commonality#190]
If [getConformanceResults](https://github.com/commonalityco/commonality/blob/d623495f33bdde3ef669ea5e1791422c8fc69cf4/packages/conformance/utils-conformance/src/get-conformance-results.ts#L19) calls without tagsData it returns an empty array.

**Comment by alec-chernicki** [comment]
@IKatsuba Thanks for filing this issue! Just so that I can re-enforce this with test coverage, how did this bug surface for you? Did you try and set up checks with by selecting all packages with`*` but there weren't any tagged packages in the project?

**Comment by alec-chernicki** [comment]
This should now be fixed in https://github.com/commonalityco/commonality/pull/194. I have released a new version of [`commonality` ](https://github.com/commonalityco/commonality/releases/tag/commonality%400.2.32), you can try the fix with version 0.2.32. Please let me know if you have any further issues!

**Comment by IKatsuba** [comment]
It is working! Thanks:)
