### ISSUE TITLE
CODEOWNERS for specific package not recognized

### ISSUE THREAD

**Issue by pawelblaszczyk5** [commonalityco/commonality#299]
Hello 👋
I can't get to work CODEOWNERS for specific package, It only works if I specify directory containing multiple packages. I have an example repository [here](https://github.com/pawelblaszczyk5/pawelblaszczyk.dev). The first line - `*` to myself works, the second one isn't. 

I've tried to debug the issue and came to this [line](https://github.com/commonalityco/commonality/blob/3257462911d3020871801d466261209c0145e345/packages/data-codeowners/src/core/get-codeowners.ts#L41). It seems like the "*" is added to my pattern and because of that it isn't selected properly. 

Or maybe I'm just missing something obvious? This's my first time with CODEOWNERS tbh 😄

BTW. Awesome work, I'm playing with commonality and I'm totally stoked about it!

**Comment by alec-chernicki** [comment]
@pawelblaszczyk5 thanks for reporting this! I'll take a look tonight and ping you when I'm able to push a fix

**Comment by alec-chernicki** [comment]
This bug has been fixed by [this PR](https://github.com/commonalityco/commonality/pull/302) and is available in `commonality@0.2.52`. I've validated the fix by running studio against your example app. Thanks again for reporting!

<img width="1681" alt="Screenshot 2024-02-10 at 12 37 25 AM 1" src="https://github.com/commonalityco/commonality/assets/6596787/10c7b3dc-4e01-4f31-bfde-9d89d6321bad">

**Comment by pawelblaszczyk5** [comment]
Thank you very much for the fix! It works flawlessly now 😊
